### ISSUE TITLE
Could you provide a toy example about the eICU dataset

### ISSUE THREAD

**Issue by YuMiaoTHU** [Google-Health/records-research#5] opened 2020-04-23 12:38 UTC
It is an excellent work!!!
It is very useful for me!
However, It takes a lot of steps for me to download the eICU dataset，Could you provide a toy example of the dataset? Or an example of input tfrecord? I want to run this code to apply to my work.
Thanks for your reply

**Comment by mp2893** [comment] 2020-04-23 14:46
We've provided the synthetic examples just for the occasion.
Please follow the steps described in the README, which begins with downloading visit_list.p.

Best,
Ed

**Comment by jonasbkemp** [comment] 2020-05-04 17:44
Duplicate of #3

**Closed as completed** 2020-05-04 17:46 UTC
